### ISSUE TITLE
Gmail 보안 이슈

### ISSUE THREAD

**Issue by Luyin** [mobile-command-center/Barracks#9]
## 에러 문구
```
{ Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuF
534-5.7.14 Qyi-tei2NKqVunlBuiF2UFpHcsyn8XU2UMbqZVMsXmi2-VcyjIZi4OfIZ4n2zZYVLpx5y_
534-5.7.14 elvafyTDGiiXYcPRYcEBeaBJzYNAxt8WndjKUhFIW-49wnTM63HJOr7G5DJFfewkJz-W6V
534-5.7.14 cYXpaoprIVBd-A> Please log in via your web browser and then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 17sm117810251pfw.65 - gsmtp
    at SMTPConnection._formatError (/home/Barracks/node_modules/nodemailer/lib/smtp-connection/index.js:781:19)
    at SMTPConnection._actionAUTHComplete (/home/Barracks/node_modules/nodemailer/lib/smtp-connection/index.js:1516:34)
    at SMTPConnection._responseActions.push.str (/home/Barracks/node_modules/nodemailer/lib/smtp-connection/index.js:554:26)
    at SMTPConnection._processResponse (/home/Barracks/node_modules/nodemailer/lib/smtp-connection/index.js:940:20)
    at SMTPConnection._onData (/home/Barracks/node_modules/nodemailer/lib/smtp-connection/index.js:746:14)
    at TLSSocket.SMTPConnection._onSocketData (/home/Barracks/node_modules/nodemailer/lib/smtp-connection/index.js:189:46)
    at TLSSocket.emit (events.js:193:13)
    at TLSSocket.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
  code: 'EAUTH',
  response:
   '534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuF\n534-5.7.14 Qyi-tei2NKqVunlBuiF2UFpHcsyn8XU2UMbqZVMsXmi2-VcyjIZi4OfIZ4n2zZYVLpx5y_\n534-5.7.14 elvafyTDGiiXYcPRYcEBeaBJzYNAxt8WndjKUhFIW-49wnTM63HJOr7G5DJFfewkJz-W6V\n534-5.7.14 cYXpaoprIVBd-A> Please log in via your web browser and then try again.\n534-5.7.14  Learn more at\n534 5.7.14  https://support.google.com/mail/answer/78754 17sm117810251pfw.65 - gsmtp',
  responseCode: 534,
  command: 'AUTH PLAIN' }
```

## 해결책

 - Oauth2 방식의 인증 적용

참고:  https://medium.com/@nickroach_50526/sending-emails-with-node-js-using-smtp-gmail-and-oauth2-316fe9c790a1

**Comment by Luyin** [comment]
## Token 만료 로직 대응 필요

https://www.woolha.com/tutorials/node-js-send-email-using-gmail-with-nodemailer-oauth-2

**Comment by Luyin** [comment]
NodeMailer러가 알아서 Token을 갱신해준다고 하는데 알아볼것

https://nodemailer.com/smtp/oauth2/

**Comment by Luyin** [comment]
- Google Oauth2.0
  - Oauth Key 방식 Client 에서만 유효함, Access Token을 브라우저 인증 없이 받아 올 수 없다.
  - Service Key 방식,
    - 특정 사용자로 메일을 보내고 싶은 경우, G Suit를 가입했을때만 가능함.
